! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Auxiliary Routines File
!
! Generated by KPP-2.3.2_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!
! File                 : gckpp_Util.F90
! Equation file        : gckpp.kpp
! Output root filename : gckpp
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Util

  USE gckpp_Parameters
  IMPLICIT NONE

CONTAINS



! User INLINED Utility Functions

! End INLINED Utility Functions

! Utility Functions from KPP_HOME/util/util
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! UTIL - Utility functions
!   Arguments :
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! ****************************************************************
!
! InitSaveData - Opens the data file for writing
!   Parameters :
!
! ****************************************************************

      SUBROUTINE InitSaveData ()

      USE gckpp_Parameters

      open(10, file='gckpp.dat')

      END SUBROUTINE InitSaveData

! End of InitSaveData function
! ****************************************************************

! ****************************************************************
!
! SaveData - Write LOOKAT species in the data file
!   Parameters :
!
! ****************************************************************

      SUBROUTINE SaveData ()

      USE gckpp_Global
      USE gckpp_Monitor

      INTEGER i

      WRITE(10,999) (TIME-TSTART)/3600.D0,  &
                   (C(LOOKAT(i))/CFACTOR, i=1,NLOOKAT)
999   FORMAT(E24.16,100(1X,E24.16))

      END SUBROUTINE SaveData

! End of SaveData function
! ****************************************************************

! ****************************************************************
!
! CloseSaveData - Close the data file
!   Parameters :
!
! ****************************************************************

      SUBROUTINE CloseSaveData ()

      USE gckpp_Parameters

      CLOSE(10)

      END SUBROUTINE CloseSaveData

! End of CloseSaveData function
! ****************************************************************

! ****************************************************************
!
! GenerateMatlab - Generates MATLAB file to load the data file
!   Parameters :
!                It will have a character string to prefix each
!                species name with.
!
! ****************************************************************

      SUBROUTINE GenerateMatlab ( PREFIX )

      USE gckpp_Parameters
      USE gckpp_Global
      USE gckpp_Monitor


      CHARACTER(LEN=8) PREFIX
      INTEGER i

      open(20, file='gckpp.m')
      write(20,*) 'load gckpp.dat;'
      write(20,990) PREFIX
990   FORMAT(A1,'c = gckpp;')
      write(20,*) 'clear gckpp;'
      write(20,991) PREFIX, PREFIX
991   FORMAT(A1,'t=',A1,'c(:,1);')
      write(20,992) PREFIX
992   FORMAT(A1,'c(:,1)=[];')

      do i=1,NLOOKAT
        write(20,993) PREFIX, SPC_NAMES(LOOKAT(i)), PREFIX, i
993     FORMAT(A1,A6,' = ',A1,'c(:,',I2,');')
      end do

      CLOSE(20)

      END SUBROUTINE GenerateMatlab

! End of GenerateMatlab function
! ****************************************************************


! End Utility Functions from KPP_HOME/util/util
! End of UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Shuffle_user2kpp - function to copy concentrations from USER to KPP
!   Arguments :
!      V_USER    - Concentration of variable species in USER's order
!      V         - Concentrations of variable species (local)
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_user2kpp ( V_USER, V )

! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)
! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)

  V(227) = V_USER(1)
  V(206) = V_USER(2)
  V(211) = V_USER(3)
  V(4) = V_USER(4)
  V(258) = V_USER(5)
  V(117) = V_USER(6)
  V(73) = V_USER(8)
  V(74) = V_USER(9)
  V(75) = V_USER(10)
  V(76) = V_USER(11)
  V(245) = V_USER(12)
  V(187) = V_USER(13)
  V(248) = V_USER(14)
  V(45) = V_USER(15)
  V(274) = V_USER(16)
  V(127) = V_USER(17)
  V(135) = V_USER(18)
  V(53) = V_USER(19)
  V(172) = V_USER(20)
  V(278) = V_USER(21)
  V(62) = V_USER(22)
  V(263) = V_USER(23)
  V(262) = V_USER(24)
  V(156) = V_USER(25)
  V(124) = V_USER(26)
  V(143) = V_USER(27)
  V(144) = V_USER(28)
  V(54) = V_USER(29)
  V(55) = V_USER(30)
  V(56) = V_USER(31)
  V(57) = V_USER(32)
  V(58) = V_USER(33)
  V(59) = V_USER(34)
  V(84) = V_USER(35)
  V(85) = V_USER(36)
  V(1) = V_USER(37)
  V(2) = V_USER(38)
  V(3) = V_USER(39)
  V(259) = V_USER(40)
  V(228) = V_USER(41)
  V(108) = V_USER(42)
  V(46) = V_USER(43)
  V(186) = V_USER(44)
  V(107) = V_USER(45)
  V(50) = V_USER(46)
  V(182) = V_USER(47)
  V(86) = V_USER(48)
  V(83) = V_USER(49)
  V(279) = V_USER(50)
  V(188) = V_USER(51)
  V(80) = V_USER(52)
  V(230) = V_USER(53)
  V(253) = V_USER(54)
  V(272) = V_USER(55)
  V(110) = V_USER(56)
  V(252) = V_USER(57)
  V(5) = V_USER(58)
  V(103) = V_USER(59)
  V(134) = V_USER(60)
  V(200) = V_USER(61)
  V(104) = V_USER(62)
  V(209) = V_USER(63)
  V(113) = V_USER(64)
  V(229) = V_USER(65)
  V(205) = V_USER(66)
  V(170) = V_USER(67)
  V(60) = V_USER(68)
  V(47) = V_USER(69)
  V(48) = V_USER(70)
  V(270) = V_USER(71)
  V(202) = V_USER(72)
  V(77) = V_USER(73)
  V(240) = V_USER(74)
  V(268) = V_USER(75)
  V(184) = V_USER(76)
  V(100) = V_USER(77)
  V(101) = V_USER(78)
  V(102) = V_USER(79)
  V(99) = V_USER(80)
  V(280) = V_USER(81)
  V(201) = V_USER(82)
  V(71) = V_USER(83)
  V(89) = V_USER(84)
  V(96) = V_USER(85)
  V(97) = V_USER(86)
  V(183) = V_USER(87)
  V(257) = V_USER(88)
  V(111) = V_USER(89)
  V(267) = V_USER(90)
  V(255) = V_USER(91)
  V(261) = V_USER(92)
  V(214) = V_USER(93)
  V(131) = V_USER(94)
  V(179) = V_USER(98)
  V(121) = V_USER(99)
  V(180) = V_USER(100)
  V(122) = V_USER(101)
  V(128) = V_USER(102)
  V(129) = V_USER(103)
  V(167) = V_USER(104)
  V(78) = V_USER(105)
  V(254) = V_USER(106)
  V(142) = V_USER(107)
  V(43) = V_USER(108)
  V(49) = V_USER(109)
  V(42) = V_USER(110)
  V(79) = V_USER(111)
  V(169) = V_USER(112)
  V(185) = V_USER(113)
  V(106) = V_USER(114)
  V(231) = V_USER(115)
  V(147) = V_USER(116)
  V(197) = V_USER(117)
  V(112) = V_USER(118)
  V(126) = V_USER(119)
  V(140) = V_USER(120)
  V(225) = V_USER(121)
  V(162) = V_USER(122)
  V(163) = V_USER(123)
  V(159) = V_USER(124)
  V(234) = V_USER(125)
  V(145) = V_USER(126)
  V(132) = V_USER(127)
  V(220) = V_USER(128)
  V(133) = V_USER(129)
  V(221) = V_USER(130)
  V(118) = V_USER(131)
  V(213) = V_USER(132)
  V(139) = V_USER(133)
  V(141) = V_USER(134)
  V(204) = V_USER(135)
  V(236) = V_USER(136)
  V(235) = V_USER(137)
  V(212) = V_USER(138)
  V(181) = V_USER(139)
  V(176) = V_USER(140)
  V(175) = V_USER(141)
  V(177) = V_USER(142)
  V(125) = V_USER(143)
  V(6) = V_USER(144)
  V(61) = V_USER(145)
  V(238) = V_USER(146)
  V(237) = V_USER(147)
  V(174) = V_USER(148)
  V(155) = V_USER(149)
  V(256) = V_USER(150)
  V(105) = V_USER(151)
  V(193) = V_USER(152)
  V(219) = V_USER(153)
  V(87) = V_USER(154)
  V(7) = V_USER(155)
  V(8) = V_USER(156)
  V(216) = V_USER(157)
  V(161) = V_USER(158)
  V(148) = V_USER(159)
  V(203) = V_USER(160)
  V(233) = V_USER(161)
  V(218) = V_USER(162)
  V(9) = V_USER(163)
  V(10) = V_USER(164)
  V(166) = V_USER(165)
  V(217) = V_USER(166)
  V(11) = V_USER(167)
  V(12) = V_USER(168)
  V(13) = V_USER(169)
  V(14) = V_USER(170)
  V(17) = V_USER(171)
  V(18) = V_USER(172)
  V(20) = V_USER(173)
  V(19) = V_USER(174)
  V(21) = V_USER(175)
  V(22) = V_USER(176)
  V(241) = V_USER(177)
  V(198) = V_USER(178)
  V(136) = V_USER(179)
  V(239) = V_USER(180)
  V(72) = V_USER(181)
  V(251) = V_USER(182)
  V(130) = V_USER(183)
  V(158) = V_USER(184)
  V(190) = V_USER(185)
  V(171) = V_USER(186)
  V(222) = V_USER(187)
  V(195) = V_USER(188)
  V(246) = V_USER(189)
  V(88) = V_USER(190)
  V(226) = V_USER(191)
  V(260) = V_USER(192)
  V(210) = V_USER(193)
  V(44) = V_USER(194)
  V(173) = V_USER(195)
  V(191) = V_USER(196)
  V(137) = V_USER(197)
  V(149) = V_USER(198)
  V(81) = V_USER(199)
  V(23) = V_USER(200)
  V(150) = V_USER(201)
  V(151) = V_USER(202)
  V(242) = V_USER(203)
  V(119) = V_USER(204)
  V(164) = V_USER(205)
  V(178) = V_USER(206)
  V(223) = V_USER(207)
  V(232) = V_USER(208)
  V(196) = V_USER(209)
  V(152) = V_USER(210)
  V(67) = V_USER(211)
  V(63) = V_USER(212)
  V(168) = V_USER(213)
  V(16) = V_USER(214)
  V(64) = V_USER(215)
  V(65) = V_USER(216)
  V(24) = V_USER(217)
  V(25) = V_USER(218)
  V(26) = V_USER(219)
  V(27) = V_USER(220)
  V(269) = V_USER(221)
  V(281) = V_USER(222)
  V(273) = V_USER(223)
  V(90) = V_USER(224)
  V(15) = V_USER(225)
  V(266) = V_USER(226)
  V(277) = V_USER(227)
  V(265) = V_USER(228)
  V(114) = V_USER(231)
  V(68) = V_USER(232)
  V(276) = V_USER(233)
  V(91) = V_USER(234)
  V(208) = V_USER(235)
  V(207) = V_USER(236)
  V(243) = V_USER(237)
  V(69) = V_USER(238)
  V(224) = V_USER(239)
  V(120) = V_USER(240)
  V(199) = V_USER(241)
  V(115) = V_USER(242)
  V(51) = V_USER(243)
  V(194) = V_USER(244)
  V(189) = V_USER(245)
  V(249) = V_USER(246)
  V(116) = V_USER(247)
  V(109) = V_USER(248)
  V(192) = V_USER(249)
  V(247) = V_USER(250)
  V(244) = V_USER(251)
  V(92) = V_USER(252)
  V(93) = V_USER(253)
  V(94) = V_USER(254)
  V(250) = V_USER(255)
  V(215) = V_USER(256)
  V(153) = V_USER(257)
  V(157) = V_USER(258)
  V(165) = V_USER(259)
  V(160) = V_USER(260)
  V(154) = V_USER(261)
  V(95) = V_USER(262)
  V(146) = V_USER(263)
  V(138) = V_USER(264)
  V(271) = V_USER(265)
  V(275) = V_USER(266)
  V(264) = V_USER(271)
  V(82) = V_USER(272)
  V(123) = V_USER(273)
  V(28) = V_USER(274)
  V(29) = V_USER(275)
  V(30) = V_USER(276)
  V(31) = V_USER(277)
  V(32) = V_USER(278)
  V(33) = V_USER(279)
  V(34) = V_USER(280)
  V(52) = V_USER(281)

END SUBROUTINE Shuffle_user2kpp

! End of Shuffle_user2kpp function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Shuffle_kpp2user - function to restore concentrations from KPP to USER
!   Arguments :
!      V         - Concentrations of variable species (local)
!      V_USER    - Concentration of variable species in USER's order
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_kpp2user ( V, V_USER )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)

  V_USER(1) = V(227)
  V_USER(2) = V(206)
  V_USER(3) = V(211)
  V_USER(4) = V(4)
  V_USER(5) = V(258)
  V_USER(6) = V(117)
  V_USER(8) = V(73)
  V_USER(9) = V(74)
  V_USER(10) = V(75)
  V_USER(11) = V(76)
  V_USER(12) = V(245)
  V_USER(13) = V(187)
  V_USER(14) = V(248)
  V_USER(15) = V(45)
  V_USER(16) = V(274)
  V_USER(17) = V(127)
  V_USER(18) = V(135)
  V_USER(19) = V(53)
  V_USER(20) = V(172)
  V_USER(21) = V(278)
  V_USER(22) = V(62)
  V_USER(23) = V(263)
  V_USER(24) = V(262)
  V_USER(25) = V(156)
  V_USER(26) = V(124)
  V_USER(27) = V(143)
  V_USER(28) = V(144)
  V_USER(29) = V(54)
  V_USER(30) = V(55)
  V_USER(31) = V(56)
  V_USER(32) = V(57)
  V_USER(33) = V(58)
  V_USER(34) = V(59)
  V_USER(35) = V(84)
  V_USER(36) = V(85)
  V_USER(37) = V(1)
  V_USER(38) = V(2)
  V_USER(39) = V(3)
  V_USER(40) = V(259)
  V_USER(41) = V(228)
  V_USER(42) = V(108)
  V_USER(43) = V(46)
  V_USER(44) = V(186)
  V_USER(45) = V(107)
  V_USER(46) = V(50)
  V_USER(47) = V(182)
  V_USER(48) = V(86)
  V_USER(49) = V(83)
  V_USER(50) = V(279)
  V_USER(51) = V(188)
  V_USER(52) = V(80)
  V_USER(53) = V(230)
  V_USER(54) = V(253)
  V_USER(55) = V(272)
  V_USER(56) = V(110)
  V_USER(57) = V(252)
  V_USER(58) = V(5)
  V_USER(59) = V(103)
  V_USER(60) = V(134)
  V_USER(61) = V(200)
  V_USER(62) = V(104)
  V_USER(63) = V(209)
  V_USER(64) = V(113)
  V_USER(65) = V(229)
  V_USER(66) = V(205)
  V_USER(67) = V(170)
  V_USER(68) = V(60)
  V_USER(69) = V(47)
  V_USER(70) = V(48)
  V_USER(71) = V(270)
  V_USER(72) = V(202)
  V_USER(73) = V(77)
  V_USER(74) = V(240)
  V_USER(75) = V(268)
  V_USER(76) = V(184)
  V_USER(77) = V(100)
  V_USER(78) = V(101)
  V_USER(79) = V(102)
  V_USER(80) = V(99)
  V_USER(81) = V(280)
  V_USER(82) = V(201)
  V_USER(83) = V(71)
  V_USER(84) = V(89)
  V_USER(85) = V(96)
  V_USER(86) = V(97)
  V_USER(87) = V(183)
  V_USER(88) = V(257)
  V_USER(89) = V(111)
  V_USER(90) = V(267)
  V_USER(91) = V(255)
  V_USER(92) = V(261)
  V_USER(93) = V(214)
  V_USER(94) = V(131)
  V_USER(98) = V(179)
  V_USER(99) = V(121)
  V_USER(100) = V(180)
  V_USER(101) = V(122)
  V_USER(102) = V(128)
  V_USER(103) = V(129)
  V_USER(104) = V(167)
  V_USER(105) = V(78)
  V_USER(106) = V(254)
  V_USER(107) = V(142)
  V_USER(108) = V(43)
  V_USER(109) = V(49)
  V_USER(110) = V(42)
  V_USER(111) = V(79)
  V_USER(112) = V(169)
  V_USER(113) = V(185)
  V_USER(114) = V(106)
  V_USER(115) = V(231)
  V_USER(116) = V(147)
  V_USER(117) = V(197)
  V_USER(118) = V(112)
  V_USER(119) = V(126)
  V_USER(120) = V(140)
  V_USER(121) = V(225)
  V_USER(122) = V(162)
  V_USER(123) = V(163)
  V_USER(124) = V(159)
  V_USER(125) = V(234)
  V_USER(126) = V(145)
  V_USER(127) = V(132)
  V_USER(128) = V(220)
  V_USER(129) = V(133)
  V_USER(130) = V(221)
  V_USER(131) = V(118)
  V_USER(132) = V(213)
  V_USER(133) = V(139)
  V_USER(134) = V(141)
  V_USER(135) = V(204)
  V_USER(136) = V(236)
  V_USER(137) = V(235)
  V_USER(138) = V(212)
  V_USER(139) = V(181)
  V_USER(140) = V(176)
  V_USER(141) = V(175)
  V_USER(142) = V(177)
  V_USER(143) = V(125)
  V_USER(144) = V(6)
  V_USER(145) = V(61)
  V_USER(146) = V(238)
  V_USER(147) = V(237)
  V_USER(148) = V(174)
  V_USER(149) = V(155)
  V_USER(150) = V(256)
  V_USER(151) = V(105)
  V_USER(152) = V(193)
  V_USER(153) = V(219)
  V_USER(154) = V(87)
  V_USER(155) = V(7)
  V_USER(156) = V(8)
  V_USER(157) = V(216)
  V_USER(158) = V(161)
  V_USER(159) = V(148)
  V_USER(160) = V(203)
  V_USER(161) = V(233)
  V_USER(162) = V(218)
  V_USER(163) = V(9)
  V_USER(164) = V(10)
  V_USER(165) = V(166)
  V_USER(166) = V(217)
  V_USER(167) = V(11)
  V_USER(168) = V(12)
  V_USER(169) = V(13)
  V_USER(170) = V(14)
  V_USER(171) = V(17)
  V_USER(172) = V(18)
  V_USER(173) = V(20)
  V_USER(174) = V(19)
  V_USER(175) = V(21)
  V_USER(176) = V(22)
  V_USER(177) = V(241)
  V_USER(178) = V(198)
  V_USER(179) = V(136)
  V_USER(180) = V(239)
  V_USER(181) = V(72)
  V_USER(182) = V(251)
  V_USER(183) = V(130)
  V_USER(184) = V(158)
  V_USER(185) = V(190)
  V_USER(186) = V(171)
  V_USER(187) = V(222)
  V_USER(188) = V(195)
  V_USER(189) = V(246)
  V_USER(190) = V(88)
  V_USER(191) = V(226)
  V_USER(192) = V(260)
  V_USER(193) = V(210)
  V_USER(194) = V(44)
  V_USER(195) = V(173)
  V_USER(196) = V(191)
  V_USER(197) = V(137)
  V_USER(198) = V(149)
  V_USER(199) = V(81)
  V_USER(200) = V(23)
  V_USER(201) = V(150)
  V_USER(202) = V(151)
  V_USER(203) = V(242)
  V_USER(204) = V(119)
  V_USER(205) = V(164)
  V_USER(206) = V(178)
  V_USER(207) = V(223)
  V_USER(208) = V(232)
  V_USER(209) = V(196)
  V_USER(210) = V(152)
  V_USER(211) = V(67)
  V_USER(212) = V(63)
  V_USER(213) = V(168)
  V_USER(214) = V(16)
  V_USER(215) = V(64)
  V_USER(216) = V(65)
  V_USER(217) = V(24)
  V_USER(218) = V(25)
  V_USER(219) = V(26)
  V_USER(220) = V(27)
  V_USER(221) = V(269)
  V_USER(222) = V(281)
  V_USER(223) = V(273)
  V_USER(224) = V(90)
  V_USER(225) = V(15)
  V_USER(226) = V(266)
  V_USER(227) = V(277)
  V_USER(228) = V(265)
  V_USER(231) = V(114)
  V_USER(232) = V(68)
  V_USER(233) = V(276)
  V_USER(234) = V(91)
  V_USER(235) = V(208)
  V_USER(236) = V(207)
  V_USER(237) = V(243)
  V_USER(238) = V(69)
  V_USER(239) = V(224)
  V_USER(240) = V(120)
  V_USER(241) = V(199)
  V_USER(242) = V(115)
  V_USER(243) = V(51)
  V_USER(244) = V(194)
  V_USER(245) = V(189)
  V_USER(246) = V(249)
  V_USER(247) = V(116)
  V_USER(248) = V(109)
  V_USER(249) = V(192)
  V_USER(250) = V(247)
  V_USER(251) = V(244)
  V_USER(252) = V(92)
  V_USER(253) = V(93)
  V_USER(254) = V(94)
  V_USER(255) = V(250)
  V_USER(256) = V(215)
  V_USER(257) = V(153)
  V_USER(258) = V(157)
  V_USER(259) = V(165)
  V_USER(260) = V(160)
  V_USER(261) = V(154)
  V_USER(262) = V(95)
  V_USER(263) = V(146)
  V_USER(264) = V(138)
  V_USER(265) = V(271)
  V_USER(266) = V(275)
  V_USER(271) = V(264)
  V_USER(272) = V(82)
  V_USER(273) = V(123)
  V_USER(274) = V(28)
  V_USER(275) = V(29)
  V_USER(276) = V(30)
  V_USER(277) = V(31)
  V_USER(278) = V(32)
  V_USER(279) = V(33)
  V_USER(280) = V(34)
  V_USER(281) = V(52)

END SUBROUTINE Shuffle_kpp2user

! End of Shuffle_kpp2user function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! GetMass - compute total mass of selected atoms
!   Arguments :
!      CL        - Concentration of all species (local)
!      Mass      - value of mass balance
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE GetMass ( CL, Mass )

! CL - Concentration of all species (local)
  REAL(kind=dp) :: CL(NSPEC)
! Mass - value of mass balance
  REAL(kind=dp) :: Mass(1)


END SUBROUTINE GetMass

! End of GetMass function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! Get_OHreactivity - returns the OH reactivity
! The OH reactivity is defined as the inverse of its lifetime.
! This routine was auto-generated using script OHreact_parser.py.
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Get_OHreactivity ( CC, RR, OHreact )

! CC - Concentrations of species (local)
  REAL(kind=dp) :: CC(NSPEC)
! RR - reaction rates (local)
  REAL(kind=dp) :: RR(NREACT)
! OHreact - OH reactivity [s-1]
  REAL(kind=dp) :: OHreact

  OHreact = RR(19)*CC(264) + RR(25)*CC(97) + RR(27)*CC(265) + 2*RR(31) + 2*RR(32) &
          + RR(33)*CC(267) + RR(34)*CC(202) + RR(37)*CC(252) + RR(38)*CC(182) + RR(44)*CC(137) &
          + RR(45)*CC(137) + RR(46)*CC(187) + RR(47)*CC(187) + RR(48)*CC(259) + RR(49)*CC(281) &
          + RR(50)*CC(257) + RR(51)*CC(269) + RR(52)*CC(183) + RR(55)*CC(111) + RR(58)*CC(273) &
          + RR(61)*CC(201) + RR(62)*CC(210) + RR(65)*CC(258) + RR(70)*CC(156) + RR(74)*CC(124) &
          + RR(75)*CC(124) + RR(79)*CC(117) + RR(89)*CC(247) + RR(90)*CC(211) + RR(91)*CC(250) &
          + RR(96)*CC(206) + RR(105)*CC(246) + RR(115)*CC(134) + RR(116)*CC(154) + RR(126)*CC(249) &
          + RR(128)*CC(229) + RR(129)*CC(229) + RR(131)*CC(205) + RR(132)*CC(226) + RR(135)*CC(240) &
          + RR(136)*CC(240) + RR(143)*CC(116) + RR(144)*CC(113) + RR(145)*CC(93) + RR(146)*CC(94) &
          + RR(147)*CC(92) + RR(148)*CC(95) + RR(149)*CC(115) + RR(150)*CC(20) + RR(151)*CC(72) &
          + RR(176)*CC(103) + RR(177)*CC(103) + RR(179)*CC(264) + RR(183)*CC(268) + RR(188)*CC(127) &
          + RR(191)*CC(278) + RR(200)*CC(86) + RR(201)*CC(84) + RR(202)*CC(108) + RR(214)*CC(282) &
          + RR(215)*CC(266) + RR(220)*CC(68) + RR(255)*CC(188) + RR(257)*CC(272) + RR(258)*CC(272) &
          + RR(259)*CC(114) + RR(260)*CC(80) + RR(261)*CC(280) + RR(262)*CC(261) + RR(263)*CC(230) &
          + RR(264)*CC(253) + RR(265)*CC(107) + RR(266)*CC(85) + RR(267)*CC(83) + RR(268)*CC(46) &
          + RR(269)*CC(99) + RR(270)*CC(101) + RR(271)*CC(102) + RR(272)*CC(100) + RR(338)*CC(142) &
          + RR(339)*CC(71) + RR(340)*CC(214) + RR(347)*CC(50) + RR(348)*CC(200) + RR(349)*CC(189) &
          + RR(363)*CC(45) + RR(364)*CC(52) + RR(365)*CC(98) + RR(373)*CC(150) + RR(374)*CC(151) &
          + RR(384)*CC(166) + RR(392)*CC(120) + RR(406)*CC(173) + RR(407)*CC(191) + RR(413)*CC(131) &
          + RR(414)*CC(88) + RR(415)*CC(104) + RR(416)*CC(87) + RR(417)*CC(90) + RR(419)*CC(216) &
          + RR(420)*CC(216) + RR(421)*CC(216) + RR(422)*CC(216) + RR(449)*CC(179) + RR(450)*CC(180) &
          + RR(451)*CC(128) + RR(452)*CC(129) + RR(453)*CC(184) + RR(454)*CC(169) + RR(455)*CC(112) &
          + RR(456)*CC(153) + RR(457)*CC(153) + RR(458)*CC(157) + RR(459)*CC(157) + RR(460)*CC(153) &
          + RR(461)*CC(157) + RR(462)*CC(165) + RR(463)*CC(160) + RR(476)*CC(118) + RR(477)*CC(132) &
          + RR(478)*CC(132) + RR(479)*CC(133) + RR(480)*CC(133) + RR(499)*CC(139) + RR(500)*CC(139) &
          + RR(501)*CC(141) + RR(502)*CC(141) + RR(503)*CC(213) + RR(504)*CC(213) + RR(505)*CC(204) &
          + RR(506)*CC(204) + RR(507)*CC(213) + RR(508)*CC(204) + RR(546)*CC(174) + RR(547)*CC(155) &
          + RR(548)*CC(174) + RR(549)*CC(155) + RR(550)*CC(155) + RR(551)*CC(174) + RR(552)*CC(155) &
          + RR(553)*CC(155) + RR(562)*CC(231) + RR(563)*CC(231) + RR(566)*CC(234) + RR(569)*CC(242) &
          + RR(571)*CC(241) + RR(572)*CC(241) + RR(575)*CC(232) + RR(576)*CC(223) + RR(577)*CC(222) &
          + RR(578)*CC(190) + RR(579)*CC(171) + RR(586)*CC(158) + RR(587)*CC(152) + RR(588)*CC(119) &
          + RR(589)*CC(178) + RR(590)*CC(164) + RR(591)*CC(130) + RR(597)*CC(136) + RR(609)*CC(149) &
          + RR(610)*CC(96) + RR(611)*CC(197) + RR(612)*CC(126) + RR(613)*CC(140) + RR(614)*CC(159) &
          + RR(615)*CC(203) + RR(616)*CC(233) + RR(618)*CC(109) + RR(619)*CC(89) + RR(621)*CC(167) &
          + RR(622)*CC(167) + RR(623)*CC(16) + RR(636)*CC(271) + RR(637)*CC(275)

END SUBROUTINE Get_OHreactivity
! End of Get_OHreactivity subroutine
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

END MODULE gckpp_Util
